fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.13.1'
    logrotate:
      repo: 'https://github.com/voxpupuli/puppet-logrotate.git'
      ref: 'v2.0.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppet-concat.git'
      ref: '2.2.0'
  symlinks:
    sfptpd: "#{source_dir}"
